name: Renovate Dependency Updates

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v39
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
